# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

PROJECT = pcre2

TARGET = LIB

!include <..\NMAKEmakefile.inc>

SRCDIR=src

INCLUDES = -I$(SRCDIR)

CFLAGS = $(CFLAGS) -DHAVE_CONFIG_H -DPCRE2_STATIC

RCFLAGS = $(RCFLAGS) /d JK_ISAPI

PDBFLAGS = -Fo$(WORKDIR)\ -Fd$(WORKDIR)\$(PROJECT)

OBJECTS = \
	$(WORKDIR)\pcre2_auto_possess.obj \
	$(WORKDIR)\pcre2_chartables.obj \
	$(WORKDIR)\pcre2_chkdint.obj \
	$(WORKDIR)\pcre2_compile.obj \
	$(WORKDIR)\pcre2_compile_cgroup.obj \
	$(WORKDIR)\pcre2_compile_class.obj \
	$(WORKDIR)\pcre2_config.obj \
	$(WORKDIR)\pcre2_context.obj \
	$(WORKDIR)\pcre2_convert.obj \
	$(WORKDIR)\pcre2_dfa_match.obj \
	$(WORKDIR)\pcre2_error.obj \
	$(WORKDIR)\pcre2_extuni.obj \
	$(WORKDIR)\pcre2_find_bracket.obj \
	$(WORKDIR)\pcre2_jit_compile.obj \
	$(WORKDIR)\pcre2_maketables.obj \
	$(WORKDIR)\pcre2_match.obj \
	$(WORKDIR)\pcre2_match_data.obj \
	$(WORKDIR)\pcre2_match_next.obj \
	$(WORKDIR)\pcre2_newline.obj \
	$(WORKDIR)\pcre2_ord2utf.obj \
	$(WORKDIR)\pcre2_pattern_info.obj \
	$(WORKDIR)\pcre2_script_run.obj \
	$(WORKDIR)\pcre2_serialize.obj \
	$(WORKDIR)\pcre2_string_utils.obj \
	$(WORKDIR)\pcre2_study.obj \
	$(WORKDIR)\pcre2_substitute.obj \
	$(WORKDIR)\pcre2_substring.obj \
	$(WORKDIR)\pcre2_tables.obj \
	$(WORKDIR)\pcre2_ucd.obj \
	$(WORKDIR)\pcre2_valid_utf.obj \
	$(WORKDIR)\pcre2_xclass.obj

ADDFILES= $(SRCDIR)\config.h $(SRCDIR)\pcre2.h $(SRCDIR)\pcre2_chartables.c

LINK_WRAPPER = $(LINK)

BUILDLIB = $(WORKDIR)\$(PROJECT).lib

all : $(WORKDIR) $(ADDFILES) $(BUILDLIB)

$(WORKDIR) :
	@$(MAKEWORKDIR)

$(SRCDIR)\config.h: config.h.win
	copy $? $@

$(SRCDIR)\pcre2.h: $(SRCDIR)\pcre2.h.generic
	copy $? $@

$(SRCDIR)\pcre2_chartables.c: $(SRCDIR)\pcre2_chartables.c.dist
	copy $? $@

{$(SRCDIR)}.c{$(WORKDIR)}.obj:
	$(CC) $(CFLAGS) $(INCLUDES) $(PDBFLAGS) $<

$(BUILDLIB): $(OBJECTS)
	$(LINK_WRAPPER) $(LFLAGS) $** /out:$(BUILDLIB)

clean:
	@-$(CLEANTARGET) 2>NUL
	del $(ADDFILES)
