name: ISAPI Windows Makefile CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        pcre: [pcre2, pcre]
        winver: [WIN10, WIN7]
        include:
          - arch: amd64
            cpu: X64
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v7
    - name: Download and install strawberryperl
      shell: bash
      run: |
            curl -L -o perl.msi https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/download/SP_54021_64bit_UCRT/strawberry-perl-5.40.2.1-64bit.msi
            msiexec.exe //q //i perl.msi
    - name: Build using Nmake
      shell: cmd
      run: |
            echo on
            call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=${{ matrix.arch }}
            cd native
            cd iis
            echo "Building for CPU=${{ matrix.cpu }} WINVER=${{ matrix.winver }} PCRE=${{ matrix.pcre }}"
            nmake -f Makefile.vc CPU=${{ matrix.cpu }} WINVER=${{ matrix.winver }} STATIC_CRT=Hybrid PCRE=${{ matrix.pcre }}
    - name: show dependents
      shell: cmd
      run: |
            echo on
            call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=${{ matrix.arch }}
            dumpbin.exe /DEPENDENTS native\iis\${{ matrix.winver }}_${{ matrix.cpu }}_DLL_RELEASE\isapi_redirect.dll
    - uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.winver }}--${{ matrix.cpu }}-${{ matrix.pcre }}-isapi_redirect
        path: native\iis\${{ matrix.winver }}_${{ matrix.cpu }}_DLL_RELEASE\isapi_redirect.dll
