name: mod_jk Windows Makefile CI

on:
  push:
  pull_request:

permissions:
  contents: read

env:
  APACHE_VERSION: 2.4.68-260617

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        winver: [WIN10]
        include:
          - arch: amd64
            cpu: X64
            httpd_arch: Win64
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v7
    - name: Download and install strawberryperl
      shell: pwsh
      run: |
            echo on
            curl -L -o perl.msi https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/download/SP_54021_64bit_UCRT/strawberry-perl-5.40.2.1-64bit.msi
            msiexec.exe /i perl.msi
    - name: Download and install ApacheLounge httpd
      shell: bash
      run: |
            curl -L -o httpd.zip https://www.apachelounge.com/download/VS18/binaries/httpd-${APACHE_VERSION}-${{ matrix.httpd_arch }}-VS18.zip
            unzip -q httpd.zip -d ApacheLounge
            echo "APACHE2_HOME_BASH=`pwd`/ApacheLounge/Apache24" >> "$GITHUB_ENV"
    - name: Build using Nmake
      shell: cmd
      run: |
            echo on
            set APACHE2_HOME=%GITHUB_WORKSPACE%\ApacheLounge\Apache24
            echo %APACHE2_HOME%
            dir %APACHE2_HOME%
            call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=${{ matrix.arch }}
            cd native
            cd apache-2.0
            echo "Building for CPU=${{ matrix.cpu }} WINVER=${{ matrix.winver }}"
            nmake -f Makefile.vc CPU=${{ matrix.cpu }} WINVER=${{ matrix.winver }} STATIC_CRT=Hybrid APACHE2_HOME=%APACHE2_HOME%
    - name: show dependents
      shell: cmd
      run: |
            echo on
            call "C:\Program Files\Microsoft Visual Studio\18\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=${{ matrix.arch }}
            dumpbin.exe /DEPENDENTS native\apache-2.0\${{ matrix.winver }}_${{ matrix.cpu }}_DLL_RELEASE\mod_jk.so
    - uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.winver }}-${{ matrix.cpu }}-mod_jk
        path: native\apache-2.0\${{ matrix.winver }}_${{ matrix.cpu }}_DLL_RELEASE\mod_jk.so
    - name: install mod_jk
      shell: bash
      run: |
            # Install module and default config
            cp -p native/apache-2.0/${{ matrix.winver }}_${{ matrix.cpu }}_DLL_RELEASE/mod_jk.so ${APACHE2_HOME_BASH}/modules/
            cp -p conf/* ${APACHE2_HOME_BASH}/conf/
            # Adjust config
            cd ${APACHE2_HOME_BASH}/conf/
            export APACHE2_HOME="$GITHUB_WORKSPACE\ApacheLounge\Apache24"
            # Replace backslashes by forward slashes
            APACHE2_HOME="${APACHE2_HOME//\\//}"
            sed -i.orig -e 's#worker.node1.port=8109#worker.node1.port=8009#' -e 's#worker.node2.activation=A#worker.node2.activation=S#' workers.properties
            sed -i.orig -e 's:# *JkMountFile conf/extra/uriworkermap.properties:JkMountFile conf/uriworkermap.properties:' httpd-jk.conf
            sed -i.orig -e 's:Listen 80:Listen 8000:' -e 's#Define SRVROOT.*#Define SRVROOT "'"$APACHE2_HOME"'"#' httpd.conf
            echo "Include conf/httpd-jk.conf" >> httpd.conf
            # Show patched config changes (debug)
            diff -w -u httpd.conf.orig httpd.conf || :
            diff -w -u httpd-jk.conf.orig httpd-jk.conf || :
            diff -w -u workers.properties.orig workers.properties || :
            # Install and start httpd service
            cd ..
            bin/httpd.exe -t
            bin/httpd.exe -k install
            bin/httpd.exe -k start
            # Check jk-status for magic string
            curl http://localhost:8000/jk-status > jk-status.out
            grep -q 'JK Status Manager for localhost:8000' jk-status.out
